# Generated by Django 5.2.14 on 2026-05-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Санат атауы")),
            ],
            options={
                "verbose_name": "Санат",
                "verbose_name_plural": "Санаттар",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Аты-жөні")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электрондық пошта"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Тақырыбы")),
                ("message", models.TextField(verbose_name="Хабарлама")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Жіберілген уақыты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Байланыс хабарламасы",
                "verbose_name_plural": "Байланыс хабарламалары",
            },
        ),
        migrations.CreateModel(
            name="AutoPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Бөлшек атауы")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Бағасы"
                    ),
                ),
                ("description", models.TextField(verbose_name="Сипаттамасы")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Қолжетімді"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Таңдаулы"),
                ),
                (
                    "image_url",
                    models.URLField(max_length=500, verbose_name="Сурет сілтемесі"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="pages.category",
                        verbose_name="Санаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автобөлшек",
                "verbose_name_plural": "Автобөлшектер",
            },
        ),
    ]
