# Generated by Django 5.2.14 on 2026-05-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Санат атауы")),
            ],
            options={
                "verbose_name": "Курс санаты",
                "verbose_name_plural": "Курс санаттары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Аты-жөні")),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Мамандығы"),
                ),
                ("bio", models.TextField(verbose_name="Өмірбаян")),
                ("photo_url", models.URLField(verbose_name="Фото URL")),
            ],
            options={
                "verbose_name": "Оқытушы",
                "verbose_name_plural": "Оқытушылар",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Курс атауы")),
                ("description", models.TextField(verbose_name="Сипаттама")),
                ("duration", models.CharField(max_length=50, verbose_name="Ұзақтығы")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Бағасы"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Танымал"),
                ),
                ("image_url", models.URLField(verbose_name="Сурет URL")),
                ("level", models.CharField(max_length=50, verbose_name="Деңгейі")),
                (
                    "start_date",
                    models.CharField(max_length=50, verbose_name="Басталуы"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="pages.coursecategory",
                        verbose_name="Санат",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="pages.instructor",
                        verbose_name="Оқытушы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курстар",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        max_length=100, verbose_name="Студенттің аты-жөні"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон нөмірі"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электрондық пошта"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Хабарлама")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Құрылған уақыты"
                    ),
                ),
                (
                    "selected_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.course",
                        verbose_name="Таңдалған курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курсқа жазылу",
                "verbose_name_plural": "Курсқа жазылулар",
                "ordering": ["-created_at"],
            },
        ),
    ]
