# Generated by Django 5.2.14 on 2026-05-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Атауы")),
                (
                    "icon_class",
                    models.CharField(max_length=50, verbose_name="Иконка классы"),
                ),
            ],
            options={
                "verbose_name": "Ыңғайлылық",
                "verbose_name_plural": "Ыңғайлылықтар",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Бөлме түрі")),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Тәулігіне бағасы"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Сыйымдылығы (адам саны)"),
                ),
                ("description", models.TextField(verbose_name="Сипаттамасы")),
                ("image_url", models.URLField(verbose_name="Сурет сілтемесі")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Қолжетімді"),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        related_name="rooms",
                        to="pages.amenity",
                        verbose_name="Ыңғайлылықтар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бөлме түрі",
                "verbose_name_plural": "Бөлмелер түрлері",
                "ordering": ["price_per_night"],
            },
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=100, verbose_name="Қонақтың аты-жөні"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон нөмірі"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронды пошта"),
                ),
                ("check_in_date", models.DateField(verbose_name="Келу күні")),
                ("check_out_date", models.DateField(verbose_name="Кету күні")),
                (
                    "guest_count",
                    models.PositiveIntegerField(verbose_name="Қонақтар саны"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Құрылған уақыты"
                    ),
                ),
                (
                    "selected_room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.roomtype",
                        verbose_name="Таңдалған бөлме түрі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Брондау өтінімі",
                "verbose_name_plural": "Брондау өтінімдері",
                "ordering": ["-created_at"],
            },
        ),
    ]
